spring:
  application:
    name: JobHunter
  datasource:
    url: jdbc:mysql://localhost:3306/jobhunterdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


#spring.application.name=JobHunter
#
## Database Connection
#spring.datasource.url=jdbc:mysql://localhost:3306/jobhunterdb
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## Hibernate/JPA Configuration
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
